FROM golang:1.20.3-bullseye AS builder
WORKDIR /
COPY go.mod go.sum ./
# Download dependencies
RUN go mod download
COPY watchdog /go/bin/watchdog

FROM alpine:latest
WORKDIR /
COPY --from=builder /go/bin/watchdog .
ENTRYPOINT ["./watchdog"]
