FROM golang:1.20.3-bullseye AS builder
WORKDIR /
COPY go.mod go.sum ./
# Download dependencies
RUN go mod download
COPY svcwatchdog /go/bin/svcwatchdog

FROM alpine:latest
WORKDIR /
COPY --from=builder /go/bin/svcwatchdog .
ENTRYPOINT ["./svcwatchdog"]
